##### Họ và tên: Lê Mạnh Cường
##### MSSV: 3123410039

# Bài toán Taci Hà Nội (Thuật toán A*)

### Bước 1: import thư viện

In [1]:
from collections import deque
from queue import PriorityQueue
import numpy as np

### Bước 2: Khởi tạo biến, heuristic và trạng thái

In [2]:
lsStart = []
lsEnd = []
move = [[0,1],[0,-1],[1,0],[-1,0]]

def heuristic(a, lsEnd):
    i, cnt = 1, 0
    for i in range(3):
        for j in range(3):
            if lsEnd[i][j]==0: continue
            cnt += (a[i][j] == lsEnd[i][j])
            pass
    return 8 - cnt

class node:
    def __init__(self, a, g, x, y):
        self.a = tuple(map(tuple, a))
        self.x = x
        self.y = y
        self.g = g
        self.h = heuristic(a, lsEnd)
        self.f = g + self.h
    def __hash__(self):
        return hash((self.a))
    def __str__(self):
        return f"Bước {self.g}: g={self.g}; h={self.h}; f={self.f}\n{np.matrix(self.a)}"
    def __eq__(self, other):
        return isinstance(other, node) and self.a == other.a
    def __lt__(self, other):
        return self.f < other.f

### Bước 3: Khởi tạo hàm Taci

In [3]:
def Taci(start, end):
    res = 0
    pq = PriorityQueue()
    pq.put(start)
    visited = set()
    visited.add(start)
    parent = {}
    parent[start] = -1
    while not pq.empty():
        u = pq.get()
        if u==end:
            end = u
            res = 1
            break
        for mv in move:
            x = mv[0] + u.x
            y = mv[1] + u.y
            if x>=0 and x<3 and y>=0 and y<3:
                v_a = list(map(list, u.a))
                v_a[x][y], v_a[u.x][u.y] = v_a[u.x][u.y], v_a[x][y]
                v = node(v_a, u.g+1, x, y)
                if v not in visited:
                    visited.add(v)
                    pq.put(v)
                    parent[v] = u
    if res == 1:
        i = end
        res = []
        while i!=-1:
            res.append(i)
            i = parent[i]
        for x in reversed(res):
            print(x)
    else: print("Không tìm thấy đường đi!!!")

### Bước 4: Chạy chương trình

In [4]:
lsStart = []
lsEnd = [[1,2,3],[4,5,6],[7,8,0]]
start = None
end = node(lsEnd, 0, 2, 2)

for i in range(1, 3+1):
    ls = list(map(int, input(f"Nhập các số phân biệt từ 0 -> 8. Mời nhập trạng thái dòng {i}: ").split(' ')))
    lsStart.append(ls)

for i in range(3):
    for j in range(3):
        if(lsStart[i][j]==0):
            start = node(lsStart, 0, i, j)
            break

Taci(start, end)

Bước 0: g=0; h=7; f=7
[[7 2 5]
 [1 8 4]
 [0 3 6]]
Bước 1: g=1; h=7; f=8
[[7 2 5]
 [0 8 4]
 [1 3 6]]
Bước 2: g=2; h=7; f=9
[[7 2 5]
 [8 0 4]
 [1 3 6]]
Bước 3: g=3; h=7; f=10
[[7 2 5]
 [8 3 4]
 [1 0 6]]
Bước 4: g=4; h=7; f=11
[[7 2 5]
 [8 3 4]
 [0 1 6]]
Bước 5: g=5; h=7; f=12
[[7 2 5]
 [0 3 4]
 [8 1 6]]
Bước 6: g=6; h=7; f=13
[[0 2 5]
 [7 3 4]
 [8 1 6]]
Bước 7: g=7; h=8; f=15
[[2 0 5]
 [7 3 4]
 [8 1 6]]
Bước 8: g=8; h=8; f=16
[[2 3 5]
 [7 0 4]
 [8 1 6]]
Bước 9: g=9; h=8; f=17
[[2 3 5]
 [7 1 4]
 [8 0 6]]
Bước 10: g=10; h=7; f=17
[[2 3 5]
 [7 1 4]
 [0 8 6]]
Bước 11: g=11; h=6; f=17
[[2 3 5]
 [0 1 4]
 [7 8 6]]
Bước 12: g=12; h=6; f=18
[[2 3 5]
 [1 0 4]
 [7 8 6]]
Bước 13: g=13; h=6; f=19
[[2 3 5]
 [1 4 0]
 [7 8 6]]
Bước 14: g=14; h=6; f=20
[[2 3 0]
 [1 4 5]
 [7 8 6]]
Bước 15: g=15; h=5; f=20
[[2 0 3]
 [1 4 5]
 [7 8 6]]
Bước 16: g=16; h=4; f=20
[[0 2 3]
 [1 4 5]
 [7 8 6]]
Bước 17: g=17; h=3; f=20
[[1 2 3]
 [0 4 5]
 [7 8 6]]
Bước 18: g=18; h=2; f=20
[[1 2 3]
 [4 0 5]
 [7 8 6]]
Bước 19: g=19; h

# Kết thúc